package com.example.repolist.common

import com.example.repolist.R

object LanguageColors {

    fun getColorRes(language: String?): Int? {
        return when (language) {
            "ABAP" -> R.color.ABAP
            "ABAP_CDS" -> R.color.ABAP_CDS
            "ActionScript" -> R.color.ActionScript
            "Ada" -> R.color.Ada
            "Adblock_Filter_List" -> R.color.Adblock_Filter_List
            "Adobe_Font_Metrics" -> R.color.Adobe_Font_Metrics
            "Agda" -> R.color.Agda
            "AGS_Script" -> R.color.AGS_Script
            "AIDL" -> R.color.AIDL
            "AL" -> R.color.AL
            "Alloy" -> R.color.Alloy
            "Alpine_Abuild" -> R.color.Alpine_Abuild
            "Altium_Designer" -> R.color.Altium_Designer
            "AMPL" -> R.color.AMPL
            "AngelScript" -> R.color.AngelScript
            "Ant_Build_System" -> R.color.Ant_Build_System
            "Antlers" -> R.color.Antlers
            "ANTLR" -> R.color.ANTLR
            "ApacheConf" -> R.color.ApacheConf
            "Apex" -> R.color.Apex
            "API_Blueprint" -> R.color.API_Blueprint
            "APL" -> R.color.APL
            "Apollo_Guidance_Computer" -> R.color.Apollo_Guidance_Computer
            "AppleScript" -> R.color.AppleScript
            "Arc" -> R.color.Arc
            "AsciiDoc" -> R.color.AsciiDoc
            "AspectJ" -> R.color.AspectJ
            "Assembly" -> R.color.Assembly
            "Astro" -> R.color.Astro
            "Asymptote" -> R.color.Asymptote
            "ATS" -> R.color.ATS
            "Augeas" -> R.color.Augeas
            "AutoHotkey" -> R.color.AutoHotkey
            "AutoIt" -> R.color.AutoIt
            "Avro_IDL" -> R.color.Avro_IDL
            "Awk" -> R.color.Awk
            "Ballerina" -> R.color.Ballerina
            "BASIC" -> R.color.BASIC
            "Batchfile" -> R.color.Batchfile
            "Beef" -> R.color.Beef
            "Berry" -> R.color.Berry
            "BibTeX" -> R.color.BibTeX
            "Bicep" -> R.color.Bicep
            "Bikeshed" -> R.color.Bikeshed
            "Bison" -> R.color.Bison
            "BitBake" -> R.color.BitBake
            "Blade" -> R.color.Blade
            "BlitzBasic" -> R.color.BlitzBasic
            "BlitzMax" -> R.color.BlitzMax
            "Bluespec" -> R.color.Bluespec
            "Boo" -> R.color.Boo
            "Boogie" -> R.color.Boogie
            "Brainfuck" -> R.color.Brainfuck
            "BrighterScript" -> R.color.BrighterScript
            "Brightscript" -> R.color.Brightscript
            "Browserslist" -> R.color.Browserslist
            "C" -> R.color.C
            "C#" -> R.color.C_Sharp
            "C++" -> R.color.Cpp
            "Cabal_Config" -> R.color.Cabal_Config
            "Cadence" -> R.color.Cadence
            "Cairo" -> R.color.Cairo
            "CameLIGO" -> R.color.CameLIGO
            "CAP_CDS" -> R.color.CAP_CDS
            "Cap'n_Proto" -> R.color.Capn_Proto
            "Ceylon" -> R.color.Ceylon
            "Chapel" -> R.color.Chapel
            "ChucK" -> R.color.ChucK
            "Cirru" -> R.color.Cirru
            "Clarion" -> R.color.Clarion
            "Clarity" -> R.color.Clarity
            "Classic_ASP" -> R.color.Classic_ASP
            "Clean" -> R.color.Clean
            "Click" -> R.color.Click
            "CLIPS" -> R.color.CLIPS
            "Clojure" -> R.color.Clojure
            "Closure_Templates" -> R.color.Closure_Templates
            "Cloud_Firestore_Security_Rules" -> R.color.Cloud_Firestore_Security_Rules
            "CMake" -> R.color.CMake
            "CodeQL" -> R.color.CodeQL
            "CoffeeScript" -> R.color.CoffeeScript
            "ColdFusion" -> R.color.ColdFusion
            "ColdFusion_CFC" -> R.color.ColdFusion_CFC
            "COLLADA" -> R.color.COLLADA
            "Common_Lisp" -> R.color.Common_Lisp
            "Common_Workflow_Language" -> R.color.Common_Workflow_Language
            "Component_Pascal" -> R.color.Component_Pascal
            "Coq" -> R.color.Coq
            "Crystal" -> R.color.Crystal
            "CSON" -> R.color.CSON
            "Csound" -> R.color.Csound
            "Csound_Document" -> R.color.Csound_Document
            "Csound_Score" -> R.color.Csound_Score
            "CSS" -> R.color.CSS
            "CSV" -> R.color.CSV
            "Cuda" -> R.color.Cuda
            "CUE" -> R.color.CUE
            "Curry" -> R.color.Curry
            "CWeb" -> R.color.CWeb
            "Cypher" -> R.color.Cypher
            "Cython" -> R.color.Cython
            "D" -> R.color.D
            "Dafny" -> R.color.Dafny
            "Darcs_Patch" -> R.color.Darcs_Patch
            "Dart" -> R.color.Dart
            "DataWeave" -> R.color.DataWeave
            "Debian_Package_Control_File" -> R.color.Debian_Package_Control_File
            "DenizenScript" -> R.color.DenizenScript
            "Dhall" -> R.color.Dhall
            "DirectX_3D_File" -> R.color.DirectX_3D_File
            "DM" -> R.color.DM
            "Dockerfile" -> R.color.Dockerfile
            "Dogescript" -> R.color.Dogescript
            "Dylan" -> R.color.Dylan
            "E" -> R.color.E
            "Earthly" -> R.color.Earthly
            "Easybuild" -> R.color.Easybuild
            "eC" -> R.color.eC
            "Ecere_Projects" -> R.color.Ecere_Projects
            "ECL" -> R.color.ECL
            "ECLiPSe" -> R.color.ECLiPSe
            "EditorConfig" -> R.color.EditorConfig
            "Eiffel" -> R.color.Eiffel
            "EJS" -> R.color.EJS
            "Elixir" -> R.color.Elixir
            "Elm" -> R.color.Elm
            "Elvish" -> R.color.Elvish
            "Emacs_Lisp" -> R.color.Emacs_Lisp
            "EmberScript" -> R.color.EmberScript
            "EQ" -> R.color.EQ
            "Erlang" -> R.color.Erlang
            "Euphoria" -> R.color.Euphoria
            "Factor" -> R.color.Factor
            "Fancy" -> R.color.Fancy
            "Fantom" -> R.color.Fantom
            "Faust" -> R.color.Faust
            "Fennel" -> R.color.Fennel
            "FIGlet_Font" -> R.color.FIGlet_Font
            "Filebench_WML" -> R.color.Filebench_WML
            "fish" -> R.color.fish
            "Fluent" -> R.color.Fluent
            "FLUX" -> R.color.FLUX
            "Forth" -> R.color.Forth
            "Fortran" -> R.color.Fortran
            "Fortran_Free_Form" -> R.color.Fortran_Free_Form
            "FreeBasic" -> R.color.FreeBasic
            "FreeMarker" -> R.color.FreeMarker
            "Frege" -> R.color.Frege
            "Futhark" -> R.color.Futhark
            "Game_Maker_Language" -> R.color.Game_Maker_Language
            "GAML" -> R.color.GAML
            "GAMS" -> R.color.GAMS
            "GAP" -> R.color.GAP
            "GCC_Machine_Description" -> R.color.GCC_Machine_Description
            "GDScript" -> R.color.GDScript
            "GEDCOM" -> R.color.GEDCOM
            "Gemini" -> R.color.Gemini
            "Genero" -> R.color.Genero
            "Genero_Forms" -> R.color.Genero_Forms
            "Genie" -> R.color.Genie
            "Genshi" -> R.color.Genshi
            "Gentoo_Ebuild" -> R.color.Gentoo_Ebuild
            "Gentoo_Eclass" -> R.color.Gentoo_Eclass
            "Gerber_Image" -> R.color.Gerber_Image
            "Gherkin" -> R.color.Gherkin
            "Git_Attributes" -> R.color.Git_Attributes
            "Git_Config" -> R.color.Git_Config
            "Git_Revision_List" -> R.color.Git_Revision_List
            "Gleam" -> R.color.Gleam
            "GLSL" -> R.color.GLSL
            "Glyph" -> R.color.Glyph
            "Gnuplot" -> R.color.Gnuplot
            "Go" -> R.color.Go
            "Go_Checksums" -> R.color.Go_Checksums
            "Go_Module" -> R.color.Go_Module
            "Golo" -> R.color.Golo
            "Gosu" -> R.color.Gosu
            "Grace" -> R.color.Grace
            "Gradle" -> R.color.Gradle
            "Grammatical_Framework" -> R.color.Grammatical_Framework
            "GraphQL" -> R.color.GraphQL
            "Groovy" -> R.color.Groovy
            "Groovy_Server_Pages" -> R.color.Groovy_Server_Pages
            "GSC" -> R.color.GSC
            "Hack" -> R.color.Hack
            "Haml" -> R.color.Haml
            "Handlebars" -> R.color.Handlebars
            "HAProxy" -> R.color.HAProxy
            "Harbour" -> R.color.Harbour
            "Haskell" -> R.color.Haskell
            "Haxe" -> R.color.Haxe
            "HiveQL" -> R.color.HiveQL
            "HLSL" -> R.color.HLSL
            "HOCON" -> R.color.HOCON
            "HolyC" -> R.color.HolyC
            "hoon" -> R.color.hoon
            "HTML" -> R.color.HTML
            "HTTP" -> R.color.HTTP
            "HXML" -> R.color.HXML
            "Hy" -> R.color.Hy
            "IDL" -> R.color.IDL
            "Idris" -> R.color.Idris
            "Ignore_List" -> R.color.Ignore_List
            "IGOR_Pro" -> R.color.IGOR_Pro
            "ImageJ_Macro" -> R.color.ImageJ_Macro
            "Imba" -> R.color.Imba
            "INI" -> R.color.INI
            "Inno_Setup" -> R.color.Inno_Setup
            "Io" -> R.color.Io
            "Ioke" -> R.color.Ioke
            "Isabelle" -> R.color.Isabelle
            "Isabelle_ROOT" -> R.color.Isabelle_ROOT
            "J" -> R.color.J
            "Janet" -> R.color.Janet
            "JAR_Manifest" -> R.color.JAR_Manifest
            "Jasmin" -> R.color.Jasmin
            "Java" -> R.color.Java
            "Java_Properties" -> R.color.Java_Properties
            "Java_Server_Pages" -> R.color.Java_Server_Pages
            "JavaScript" -> R.color.JavaScript
            "Jest_Snapshot" -> R.color.Jest_Snapshot
            "JetBrains_MPS" -> R.color.JetBrains_MPS
            "JFlex" -> R.color.JFlex
            "Jinja" -> R.color.Jinja
            "Jison" -> R.color.Jison
            "Jison_Lex" -> R.color.Jison_Lex
            "Jolie" -> R.color.Jolie
            "jq" -> R.color.jq
            "JSON" -> R.color.JSON
            "JSON_with_Comments" -> R.color.JSON_with_Comments
            "JSON5" -> R.color.JSON5
            "JSONiq" -> R.color.JSONiq
            "JSONLD" -> R.color.JSONLD
            "Jsonnet" -> R.color.Jsonnet
            "Julia" -> R.color.Julia
            "Jupyter_Notebook" -> R.color.Jupyter_Notebook
            "just" -> R.color.just
            "Kaitai_Struct" -> R.color.Kaitai_Struct
            "KakouneScript" -> R.color.KakouneScript
            "KiCad_Layout" -> R.color.KiCad_Layout
            "KiCad_Legacy_Layout" -> R.color.KiCad_Legacy_Layout
            "KiCad_Schematic" -> R.color.KiCad_Schematic
            "Kotlin" -> R.color.Kotlin
            "KRL" -> R.color.KRL
            "kvlang" -> R.color.kvlang
            "LabVIEW" -> R.color.LabVIEW
            "Lark" -> R.color.Lark
            "Lasso" -> R.color.Lasso
            "Latte" -> R.color.Latte
            "Less" -> R.color.Less
            "Lex" -> R.color.Lex
            "LFE" -> R.color.LFE
            "LigoLANG" -> R.color.LigoLANG
            "LilyPond" -> R.color.LilyPond
            "Liquid" -> R.color.Liquid
            "Literate_Agda" -> R.color.Literate_Agda
            "Literate_CoffeeScript" -> R.color.Literate_CoffeeScript
            "Literate_Haskell" -> R.color.Literate_Haskell
            "LiveScript" -> R.color.LiveScript
            "LLVM" -> R.color.LLVM
            "Logtalk" -> R.color.Logtalk
            "LOLCODE" -> R.color.LOLCODE
            "LookML" -> R.color.LookML
            "LSL" -> R.color.LSL
            "Lua" -> R.color.Lua
            "Macaulay2" -> R.color.Macaulay2
            "Makefile" -> R.color.Makefile
            "Mako" -> R.color.Mako
            "Markdown" -> R.color.Markdown
            "Marko" -> R.color.Marko
            "Mask" -> R.color.Mask
            "Mathematica" -> R.color.Mathematica
            "MATLAB" -> R.color.MATLAB
            "Max" -> R.color.Max
            "MAXScript" -> R.color.MAXScript
            "mcfunction" -> R.color.mcfunction
            "Mercury" -> R.color.Mercury
            "Mermaid" -> R.color.Mermaid
            "Meson" -> R.color.Meson
            "Metal" -> R.color.Metal
            "MiniYAML" -> R.color.MiniYAML
            "Mint" -> R.color.Mint
            "Mirah" -> R.color.Mirah
            "mIRC_Script" -> R.color.mIRC_Script
            "MLIR" -> R.color.MLIR
            "Modelica" -> R.color.Modelica
            "Monkey_C" -> R.color.Monkey_C
            "MoonScript" -> R.color.MoonScript
            "Motoko" -> R.color.Motoko
            "Motorola_68K_Assembly" -> R.color.Motorola_68K_Assembly
            "Move" -> R.color.Move
            "MQL4" -> R.color.MQL4
            "MQL5" -> R.color.MQL5
            "MTML" -> R.color.MTML
            "mupad" -> R.color.mupad
            "Mustache" -> R.color.Mustache
            "nanorc" -> R.color.nanorc
            "Nasal" -> R.color.Nasal
            "NCL" -> R.color.NCL
            "Nearley" -> R.color.Nearley
            "Nemerle" -> R.color.Nemerle
            "nesC" -> R.color.nesC
            "NetLinx" -> R.color.NetLinx
            "NetLogo" -> R.color.NetLogo
            "NewLisp" -> R.color.NewLisp
            "Nextflow" -> R.color.Nextflow
            "Nginx" -> R.color.Nginx
            "Nim" -> R.color.Nim
            "Nit" -> R.color.Nit
            "Nix" -> R.color.Nix
            "NPM_Config" -> R.color.NPM_Config
            "Nu" -> R.color.Nu
            "NumPy" -> R.color.NumPy
            "Nunjucks" -> R.color.Nunjucks
            "NWScript" -> R.color.NWScript
            "ObjectScript" -> R.color.ObjectScript
            "OCaml" -> R.color.OCaml
            "Odin" -> R.color.Odin
            "Omgrofl" -> R.color.Omgrofl
            "ooc" -> R.color.ooc
            "Opal" -> R.color.Opal
            "Open_Policy_Agent" -> R.color.Open_Policy_Agent
            "OpenAPI_Specification_v2" -> R.color.OpenAPI_Specification_v2
            "OpenAPI_Specification_v3" -> R.color.OpenAPI_Specification_v3
            "OpenCL" -> R.color.OpenCL
            "OpenEdge_ABL" -> R.color.OpenEdge_ABL
            "OpenQASM" -> R.color.OpenQASM
            "OpenSCAD" -> R.color.OpenSCAD
            "Option_List" -> R.color.Option_List
            "Org" -> R.color.Org
            "Oxygene" -> R.color.Oxygene
            "Oz" -> R.color.Oz
            "P4" -> R.color.P4
            "Pan" -> R.color.Pan
            "Papyrus" -> R.color.Papyrus
            "Parrot" -> R.color.Parrot
            "Pascal" -> R.color.Pascal
            "Pawn" -> R.color.Pawn
            "PDDL" -> R.color.PDDL
            "Pep8" -> R.color.Pep8
            "Perl" -> R.color.Perl
            "PHP" -> R.color.PHP
            "PicoLisp" -> R.color.PicoLisp
            "PigLatin" -> R.color.PigLatin
            "Pike" -> R.color.Pike
            "PLpgSQL" -> R.color.PLpgSQL
            "PLSQL" -> R.color.PLSQL
            "PogoScript" -> R.color.PogoScript
            "Polar" -> R.color.Polar
            "Portugol" -> R.color.Portugol
            "PostCSS" -> R.color.PostCSS
            "PostScript" -> R.color.PostScript
            "PowerBuilder" -> R.color.PowerBuilder
            "PowerShell" -> R.color.PowerShell
            "Prisma" -> R.color.Prisma
            "Processing" -> R.color.Processing
            "Procfile" -> R.color.Procfile
            "Prolog" -> R.color.Prolog
            "Promela" -> R.color.Promela
            "Propeller_Spin" -> R.color.Propeller_Spin
            "Pug" -> R.color.Pug
            "Puppet" -> R.color.Puppet
            "PureBasic" -> R.color.PureBasic
            "PureScript" -> R.color.PureScript
            "Python" -> R.color.Python
            "Python_console" -> R.color.Python_console
            "Python_traceback" -> R.color.Python_traceback
            "q" -> R.color.q
            "QML" -> R.color.QML
            "Qt_Script" -> R.color.Qt_Script
            "Quake" -> R.color.Quake
            "R" -> R.color.R
            "Racket" -> R.color.Racket
            "Ragel" -> R.color.Ragel
            "Raku" -> R.color.Raku
            "RAML" -> R.color.RAML
            "Rascal" -> R.color.Rascal
            "RDoc" -> R.color.RDoc
            "Reason" -> R.color.Reason
            "ReasonLIGO" -> R.color.ReasonLIGO
            "Rebol" -> R.color.Rebol
            "Record_Jar" -> R.color.Record_Jar
            "Red" -> R.color.Red
            "Regular_Expression" -> R.color.Regular_Expression
            "ReScript" -> R.color.ReScript
            "reStructuredText" -> R.color.reStructuredText
            "REXX" -> R.color.REXX
            "Ring" -> R.color.Ring
            "Riot" -> R.color.Riot
            "RMarkdown" -> R.color.RMarkdown
            "RobotFramework" -> R.color.RobotFramework
            "Roff" -> R.color.Roff
            "Roff_Manpage" -> R.color.Roff_Manpage
            "Rouge" -> R.color.Rouge
            "RouterOS_Script" -> R.color.RouterOS_Script
            "RPGLE" -> R.color.RPGLE
            "Ruby" -> R.color.Ruby
            "RUNOFF" -> R.color.RUNOFF
            "Rust" -> R.color.Rust
            "SaltStack" -> R.color.SaltStack
            "SAS" -> R.color.SAS
            "Sass" -> R.color.Sass
            "Scala" -> R.color.Scala
            "Scaml" -> R.color.Scaml
            "Scenic" -> R.color.Scenic
            "Scheme" -> R.color.Scheme
            "Scilab" -> R.color.Scilab
            "SCSS" -> R.color.SCSS
            "sed" -> R.color.sed
            "Self" -> R.color.Self
            "ShaderLab" -> R.color.ShaderLab
            "Shell" -> R.color.Shell
            "ShellCheck_Config" -> R.color.ShellCheck_Config
            "Shen" -> R.color.Shen
            "Simple_File_Verification" -> R.color.Simple_File_Verification
            "Singularity" -> R.color.Singularity
            "Slash" -> R.color.Slash
            "Slice" -> R.color.Slice
            "Slim" -> R.color.Slim
            "Smalltalk" -> R.color.Smalltalk
            "Smarty" -> R.color.Smarty
            "SmPL" -> R.color.SmPL
            "Solidity" -> R.color.Solidity
            "SourcePawn" -> R.color.SourcePawn
            "SPARQL" -> R.color.SPARQL
            "SQF" -> R.color.SQF
            "SQL" -> R.color.SQL
            "SQLPL" -> R.color.SQLPL
            "Squirrel" -> R.color.Squirrel
            "SRecode_Template" -> R.color.SRecode_Template
            "Stan" -> R.color.Stan
            "Standard_ML" -> R.color.Standard_ML
            "Starlark" -> R.color.Starlark
            "Stata" -> R.color.Stata
            "STL" -> R.color.STL
            "StringTemplate" -> R.color.StringTemplate
            "Stylus" -> R.color.Stylus
            "SubRip_Text" -> R.color.SubRip_Text
            "SugarSS" -> R.color.SugarSS
            "SuperCollider" -> R.color.SuperCollider
            "Svelte" -> R.color.Svelte
            "SVG" -> R.color.SVG
            "Swift" -> R.color.Swift
            "SystemVerilog" -> R.color.SystemVerilog
            "Talon" -> R.color.Talon
            "Tcl" -> R.color.Tcl
            "Terra" -> R.color.Terra
            "TeX" -> R.color.TeX
            "Textile" -> R.color.Textile
            "TextMate_Properties" -> R.color.TextMate_Properties
            "Thrift" -> R.color.Thrift
            "TI_Program" -> R.color.TI_Program
            "TLA" -> R.color.TLA
            "TOML" -> R.color.TOML
            "TSQL" -> R.color.TSQL
            "TSV" -> R.color.TSV
            "TSX" -> R.color.TSX
            "Turing" -> R.color.Turing
            "Twig" -> R.color.Twig
            "TXL" -> R.color.TXL
            "TypeScript" -> R.color.TypeScript
            "Unified_Parallel_C" -> R.color.Unified_Parallel_C
            "Unity3D_Asset" -> R.color.Unity3D_Asset
            "Unix_Assembly" -> R.color.Unix_Assembly
            "Uno" -> R.color.Uno
            "UnrealScript" -> R.color.UnrealScript
            "UrWeb" -> R.color.UrWeb
            "V" -> R.color.V
            "Vala" -> R.color.Vala
            "Valve_Data_Format" -> R.color.Valve_Data_Format
            "VBA" -> R.color.VBA
            "VBScript" -> R.color.VBScript
            "VCL" -> R.color.VCL
            "Velocity_Template_Language" -> R.color.Velocity_Template_Language
            "Verilog" -> R.color.Verilog
            "VHDL" -> R.color.VHDL
            "Vim_Help_File" -> R.color.Vim_Help_File
            "Vim_Script" -> R.color.Vim_Script
            "Vim_Snippet" -> R.color.Vim_Snippet
            "Volt" -> R.color.Volt
            "Vue" -> R.color.Vue
            "Vyper" -> R.color.Vyper
            "wdl" -> R.color.wdl
            "Web_Ontology_Language" -> R.color.Web_Ontology_Language
            "WebAssembly" -> R.color.WebAssembly
            "Whiley" -> R.color.Whiley
            "Wikitext" -> R.color.Wikitext
            "Windows_Registry_Entries" -> R.color.Windows_Registry_Entries
            "wisp" -> R.color.wisp
            "Witcher_Script" -> R.color.Witcher_Script
            "Wollok" -> R.color.Wollok
            "World_of_Warcraft_Addon_Data" -> R.color.World_of_Warcraft_Addon_Data
            "Wren" -> R.color.Wren
            "X10" -> R.color.X10
            "xBase" -> R.color.xBase
            "XC" -> R.color.XC
            "XML" -> R.color.XML
            "XML_Property_List" -> R.color.XML_Property_List
            "Xojo" -> R.color.Xojo
            "Xonsh" -> R.color.Xonsh
            "XQuery" -> R.color.XQuery
            "XSLT" -> R.color.XSLT
            "Xtend" -> R.color.Xtend
            "Yacc" -> R.color.Yacc
            "YAML" -> R.color.YAML
            "YARA" -> R.color.YARA
            "YASnippet" -> R.color.YASnippet
            "Yul" -> R.color.Yul
            "ZAP" -> R.color.ZAP
            "ZenScript" -> R.color.ZenScript
            "Zephir" -> R.color.Zephir
            "Zig" -> R.color.Zig
            "ZIL" -> R.color.ZIL
            "Zimpl" -> R.color.Zimpl
            else -> null
        }
    }

}